# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160505_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_id', models.CharField(max_length=100, verbose_name='Distribuição')),
                ('release', models.CharField(max_length=100, verbose_name='Release')),
                ('codename', models.CharField(max_length=100, verbose_name='Codename')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
    ]
