# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160505_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_system', models.CharField(max_length=100, verbose_name='Sistema de arquivos')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tamanho')),
                ('used', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Utilizado')),
                ('free', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Livre')),
                ('free_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual Livre')),
                ('mounted_in', models.CharField(max_length=100, verbose_name='Montado em')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total')),
                ('used', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Utilizado')),
                ('free', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Livre')),
                ('percent_used', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual Utilizado')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Machine')),
            ],
        ),
    ]
