# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20160505_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='machine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Machine'),
        ),
    ]
