# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20160507_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='cpu_cores',
            field=models.IntegerField(default=0, verbose_name='CPU cores'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='percent_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual Utilizado'),
        ),
    ]
