# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_cpu_inserted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inserido em'),
        ),
        migrations.AddField(
            model_name='memory',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inserido em'),
        ),
        migrations.AddField(
            model_name='os',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inserido em'),
        ),
    ]
