# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_disc_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='free',
            field=models.CharField(max_length=100, verbose_name='Livre'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='size',
            field=models.CharField(max_length=100, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='used',
            field=models.CharField(max_length=100, verbose_name='Utilizado'),
        ),
    ]
