# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20160509_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('status', models.IntegerField(choices=[(1, 'Running'), (2, 'Stopped')])),
            ],
        ),
    ]
