# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20160512_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.IntegerField(choices=[(1, 'Running'), (2, 'Stopped')], verbose_name='Status'),
        ),
    ]
