# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alertconfig_cpualert'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpualert',
            name='alert_level',
            field=models.IntegerField(choices=[(1, 'Warning'), (2, 'Critical')], null=True, verbose_name='Nível de alerta'),
        ),
        migrations.AddField(
            model_name='cpualert',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inserido em'),
        ),
        migrations.AddField(
            model_name='cpualert',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Machine'),
        ),
        migrations.AddField(
            model_name='cpualert',
            name='percent_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual Utilizado'),
        ),
    ]
