# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_memoryalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.IntegerField(choices=[(1, 'Warning'), (2, 'Critical')], null=True, verbose_name='Nível de alerta')),
                ('percent_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual Utilizado')),
                ('partition', models.CharField(max_length=100, verbose_name='Partição')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inserido em')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Machine')),
            ],
        ),
    ]
